# Generated by Django 3.1.6 on 2021-06-11 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0006_contact_works'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='images')),
                ('description', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name': 'team',
                'verbose_name_plural': 'teams',
            },
        ),
        migrations.AlterModelOptions(
            name='services',
            options={'ordering': ('name',), 'verbose_name': 'service', 'verbose_name_plural': 'services'},
        ),
        migrations.AlterModelOptions(
            name='works',
            options={'ordering': ('name',), 'verbose_name': 'work', 'verbose_name_plural': 'works'},
        ),
        migrations.RemoveField(
            model_name='services',
            name='description',
        ),
        migrations.RemoveField(
            model_name='works',
            name='description',
        ),
    ]
